const EErrors = {
    ROUTING_ERROR:1,
    INVALID_TYPES_ERROR:2,
    NOT_ACCESS_AUTORIZATION:3,
    AUTHOTENTICATION_ERROR:4,
    DUPLICATE_PRODUCT_CODE_ERROR: 5,
    DATABASE_ERROR:6
}

export default EErrors;